export const selector = {
    //login 
    usernameInput : "Enter your email",
    passwordInput : "//input[@id='password']",

    //iFrame src & tags
    src : "https://connect.dev.pact.optimizoryapps.com/jira/pactHome.273ce18b3d6fd0ac26db.html?xdm_e=https%3A%2F%2Fotpl-demo.atlassian.net&xdm_c=channel-com.optimizory.jira.plugins.cmo__cmo-top-pact-home&cp=&xdm_deprecated_addon_key_do_not_use=com.optimizory.jira.plugins.cmo&lic=active&cv=1001.0.0-SNAPSHOT",
    newSrc : "https://connect.dev.pact.optimizoryapps.com/jira/pactDetails.5e4a91d862f70db768d2.html?xdm_e=https%3A%2F%2Fotpl-demo.atlassian.net&xdm_c=channel-com.optimizory.jira.plugins.cmo__cmo-issue-left-panel&cp=&xdm_deprecated_addon_key_do_not_use=com.optimizory.jira.plugins.cmo&lic=active&cv=1001.0.0-SNAPSHOT",
    configSrc : "https://connect.dev.pact.optimizoryapps.com/jira/pactHome.273ce18b3d6fd0ac26db.html?xdm_e=https%3A%2F%2Fotpl-demo.atlassian.net&xdm_c=channel-com.optimizory.jira.plugins.cmo__cmo-home-page&cp=&xdm_deprecated_addon_key_do_not_use=com.optimizory.jira.plugins.cmo&lic=active&cv=1001.0.0-SNAPSHOT",
    sanSrc : "https://connect.dev.pact.optimizoryapps.com/jira/pactConfigure.f3a6f6ebdcedc42fead3.html?xdm_e=https%3A%2F%2Fotpl-demo.atlassian.net&xdm_c=channel-com.optimizory.jira.plugins.cmo__cmo-config-page&cp=&xdm_deprecated_addon_key_do_not_use=com.optimizory.jira.plugins.cmo&lic=active&cv=1001.0.0-SNAPSHOT",

    //buttons
    button : 'button',
    op : 'option',
    label : 'label',
    filter : 'Filter',
    closeFilter : 'Close filter',
    selDev : 'Selected for Development',
    done : 'Done',
    inProgress : 'In Progress',
    menu : "menuitem",
    pact : "Pact Details",
    sorting : "div[class='sc-khjJXk brfSVF'] button[type='button']",
    apps : "issue-view-foundation.quick-add.quick-add-items-compact.apps-button-dropdown--trigger",
    pg4 : "//button[@aria-label='page 4']",
    pg5 : "//button[@aria-label='page 5']",
    pt5 : "//div[normalize-space()='PT-5']",
    pt1 : "//div[normalize-space()='PT-1']",
    page2 : "div[class='sc-blmEgr cTssHX'] button[aria-label='page 2']",
    status : "//button[@id='issue.fields.status-view.status-button']",
    menuItem : 'ref-spotlight-target-status-spotlight',
    refresh : "div[class='refresh-button'] span[class='css-1wits42']",
    expand58 : "Expand row PT-58",
    expand : "//div[@class='css-xfp5fq']//div[3]//div[1]//span[1]//span[1]//button[1]//span[1]//span[1]",
    expand54 : "Expand row PT-54",
    help : "//span[@aria-label='Get help']",
    license : "Licensing Agreement",
    training : "Training Services Contract",
    documentation : 'Documentation Documentation',
    ticket : 'Create Support Ticket Create',
    feedback : 'Leave Feedback Leave Feedback',
    bookDemo : 'Book a Demo Book a Demo',
    website : 'Visit Website Visit Website',
    contact : 'Contact Us Contact Us',
    toggle : "//div[@class='css-17tpdod']",
    configuration : "Configuration",

    //Config Options
    task : 'Task',
    blocks : 'Blocks',
    relates : 'Relates',
    subtask : 'Sub-task',
    story : 'Story',
    cloners : 'Cloners',
    cil : 'Custom Issue Linking',
    forms : "Submitted forms",
    estCost : 'Estimated cost',
    submit : 'Submit',

    //Config tabs 
    CIT : '.react-select__input-container',
    CLR : 'div:nth-child(3) > .css-q5x77e > .css-7kwkvx > .css-rq8zrp-container > .react-select__control > .react-select__value-container',
    CLR2 : 'div:nth-child(3) > .css-q5x77e > .css-7kwkvx > .css-rq8zrp-container > .react-select__control > .react-select__value-container > .react-select__input-container',
    RIT : 'div:nth-child(4) > .css-q5x77e > .css-7kwkvx > .css-rq8zrp-container > .react-select__control',
    RIT2 : 'div:nth-child(4) > .css-q5x77e > .css-7kwkvx > .css-rq8zrp-container > .react-select__control > .react-select__value-container > .react-select__input-container',
    RIT3 : 'div:nth-child(4) > .css-q5x77e > .css-7kwkvx > .css-rq8zrp-container > .react-select__control > .react-select__indicators > .react-select__indicator',
    NL : 'div:nth-child(5) > .css-q5x77e > .css-7kwkvx > .css-rq8zrp-container > .react-select__control > .react-select__value-container',
    NL2 : 'div:nth-child(5) > .css-q5x77e > .css-7kwkvx > .css-rq8zrp-container > .react-select__control > .react-select__value-container > .react-select__input-container',
    EC : 'div:nth-child(6) > .css-q5x77e > .css-7kwkvx > .css-rq8zrp-container > .react-select__control > .react-select__value-container',
    OC : 'div:nth-child(6) > .css-q5x77e > .css-7kwkvx > .css-rq8zrp-container > .react-select__control > .react-select__value-container > .react-select__input-container',

    //New Additions Link
    issueType : '+ Add New Issue Type',
    linkType : '+ Add New Link Type',
    customField : '+ Add New Custom Field',
    textbox : 'textbox',
    nameIT : 'Issue Type Name',
    nameLT : 'Link Type Name',
    create : 'Create',
    inward : 'Inward Link',
    outward : 'Outward Link',
    fieldName : 'Field Name',
};