export const selector = {
    //login 
    usernameInput : "Enter your email",
    passwordInput : "//input[@id='password']",

    //iFrame src & tags
    src : "https://connect.dev.pact.optimizoryapps.com/jira/pactHome.273ce18b3d6fd0ac26db.html?xdm_e=https%3A%2F%2Fotpl-demo.atlassian.net&xdm_c=channel-com.optimizory.jira.plugins.cmo__cmo-top-pact-home&cp=&xdm_deprecated_addon_key_do_not_use=com.optimizory.jira.plugins.cmo&lic=active&cv=1001.0.0-SNAPSHOT",
    newSrc : "https://connect.dev.pact.optimizoryapps.com/jira/pactDetails.5e4a91d862f70db768d2.html?xdm_e=https%3A%2F%2Fotpl-demo.atlassian.net&xdm_c=channel-com.optimizory.jira.plugins.cmo__cmo-issue-left-panel&cp=&xdm_deprecated_addon_key_do_not_use=com.optimizory.jira.plugins.cmo&lic=active&cv=1001.0.0-SNAPSHOT",

    //buttons
    button : 'button',
    label : 'label',
    filter : 'Filter',
    closeFilter : 'Close filter',
    selDev : 'Selected for Development',
    done : 'Done',
    inProgress : 'In Progress',
    menu : "menuitem",
    pact : "Pact Details",
    sorting : "div[class='sc-khjJXk brfSVF'] button[type='button']",
    apps : "issue-view-foundation.quick-add.quick-add-items-compact.apps-button-dropdown--trigger",
    pg4 : "//button[@aria-label='page 4']",
    pg5 : "//button[@aria-label='page 5']",
    pt5 : "//div[normalize-space()='PT-5']",
    pt1 : "//div[normalize-space()='PT-1']",
    page2 : "div[class='sc-blmEgr cTssHX'] button[aria-label='page 2']",
    status : "//button[@id='issue.fields.status-view.status-button']",
    menuItem : 'ref-spotlight-target-status-spotlight',
    refresh : "div[class='refresh-button'] span[class='css-1wits42']",
    expand58 : "Expand row PT-58",
    expand : "//div[@class='css-xfp5fq']//div[3]//div[1]//span[1]//span[1]//button[1]//span[1]//span[1]",
    expand54 : "Expand row PT-54",
    help : "//span[@aria-label='Get help']",
    license : "Licensing Agreement",
    training : "Training Services Contract",
    documentation : 'Documentation Documentation',
    ticket : 'Create Support Ticket Create',
    feedback : 'Leave Feedback Leave Feedback',
    bookDemo : 'Book a Demo Book a Demo',
    website : 'Visit Website Visit Website',
    contact : 'Contact Us Contact Us',
};